Database:
  Enabled: false
  Host: localhost
  Port: 3306
  Database: AvN_Reputation
  Username: root
  Password: changeMe!

ReputationFactions:
  # The unique name of a reputation faction.
  example:
    # The display name of the faction in commands and GUIs.
    DisplayName: "&7Example"
    # The item displayed for this faction in the '/reputation' menu. Supports Avalon Items.
    IconItem: EMERALD
    # The maximum reputation level a player can get with this faction.
    MaxLevel: 20
    # The minimum amount of reputation required to level up the first time.
    FirstLevelCost: 25
    # The maximum amount of reputation required to level up the last time.
    LastLevelCost: 5000
    # A curve that manipulates how steeply or inversely the reputation cost for each level increases.
    RepCurve: -0.65
    # Information about reputation currencies for trading and shops
    Currency:
      # Whether or not to enable this feature for this faction
      Enabled: true
      # What item to use as this faction's currency. Can be an Avalon Item.
      Item: EMERALD
      # How many reputation points the player must get before being rewarded a currency item
      CurrencyRate: 25
    # A list of reputation sources that manipulate how the player gains or loses reputation with this faction.
    # Visit https://github.com/destradious/AvN-Reputation/wiki/Reputation-Sources-&-Triggers for available sources.
    Sources:
      # A reputation trigger name
      KILL_ENDERMAN:
        # How much reputation will be gained upon completing this task. (Negative values are allowed.)
        Reputation: 5
        # The human-readable display name of this source in the faction info menu.
        DisplayName: "&dKill Endermen"
        # The item that will represent this source in the faction info menu. Supports Avalon Items.
        IconItem: ENDER_PEARL
      KILL_MONSTER:
        Reputation: 1
        DisplayName: "&cKill Hostile Monsters"
        IconItem: mythrilingot
      BREAK_SPAWNER:
        Reputation: 100
        DisplayName: "&cBreak Mob Spawners"
        IconItem: SPAWNER
    # A list of dynamic sources. Dynamic sources area collection of other sources that will randomly be chosen.
    # In this example, ItemList1 will randomly add one of the five CRAFT_[item] sources listed below on startup.
    # Dynamic sources can also be force-updated with '/reputation updatesources'
    DynamicSources:
      # The name of this dynamic source. Must be unique, but can otherwise be whatever you like.
      DiamondToolsSource:
        CRAFT_DIAMOND_SHOVEL:
          Reputation: 7
          DisplayName: "&bCraft Diamond Shovels"
          IconItem: DIAMOND_SHOVEL
        CRAFT_DIAMOND_SWORD:
          Reputation: 10
          DisplayName: "&bCraft Diamond Sword"
          IconItem: DIAMOND_SWORD
        CRAFT_DIAMOND_HOE:
          Reputation: 10
          DisplayName: "&bCraft Diamond Hoe"
          IconItem: DIAMOND_HOE
        CRAFT_DIAMOND_PICKAXE:
          Reputation: 13
          DisplayName: "&bCraft Diamond Pickaxe"
          IconItem: DIAMOND_PICKAXE
        CRAFT_DIAMOND_AXE:
          Reputation: 13
          DisplayName: "&bCraft Diamond Axe"
          IconItem: DIAMOND_AXE
    # Commands to execute when a player reaches a specific reputation level.
    Commands:
      # The commands that will fire when a player reaches this level. Use <player> for the player's display name.
      5:
        - "minecraft:say <player> reached reputation level 5 with Example!"
        - "minecraft:give <player> diamond"
      10:
        - "minecraft:give <player> netherstar"
  anotherexample:
    DisplayName: "&2Another Example"
    MaxLevel: 15
    FirstLevelCost: 25
    LastLevelCost: 5000
    RepCurve: -0.65
    Sources:
      KILL_MONSTER:
        Reputation: 2
        DisplayName: "&cKill Hostile Monsters"